### ISSUE TITLE
Add Nic to listener might be failed

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#113]
DEBUG:zstacklib.utils.shell:iptables -D INPUT -d 10.0.101.227 -p tcp --dport 22 --syn -j DROP
2015-08-27 07:51:29,657 WARNING [zstacklib.utils.rollback] a unhandled exception happens:
Traceback (most recent call last):
  File "/var/lib/zstack/virtualenv/virtualrouter/lib/python2.6/site-packages/zstacklib/utils/rollback.py", line 26, in wrap
    return func(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/virtualrouter/lib/python2.6/site-packages/virtualrouter/plugins/lb.py", line 89, in _refresh
    shell.call("iptables -D INPUT -d %s -p tcp --dport %s --syn -j DROP" % (to.vip, to.loadBalancerPort))
  File "/var/lib/zstack/virtualenv/virtualrouter/lib/python2.6/site-packages/zstacklib/utils/shell.py", line 51, in call
    return ShellCmd(cmd, workdir)(exception)
  File "/var/lib/zstack/virtualenv/virtualrouter/lib/python2.6/site-packages/zstacklib/utils/shell.py", line 45, in __call__
    raise ShellError('\n'.join(err))
ShellError: failed to execute shell command: iptables -D INPUT -d 10.0.101.227 -p tcp --dport 22 --syn -j DROP
return code: 1
stdout:
stderr: iptables: Bad rule (does a matching rule exist in that chain?).

**Comment by youyk** [comment]
[Async call]: [LogInByAccountAction] Success
2015-08-27 19:51:28,862 DEBUG [apibinding.api] async call[url: http://10.0.101.20:8080/zstack/api/, request: {"org.zstack.network.service.lb.APIAddVmNicToLoadBalancerMsg": {"session": {"uuid": "ab218508bcaa4c80a342716e1ccb2cd1"}, "listenerUuid": "c4b14cfe479c4719bf1d0de10664aadb", "sessionUuid": "ab218508bcaa4c80a342716e1ccb2cd1", "vmNicUuids": ["9ed1658152134b1890a11b2a9a247f3b", "dcc4ad7a12724a1cafdebac572410147", "f9fed53e23ea43a490ce2122d166daee"]}}]
2015-08-27 19:51:29,886 DEBUG [apibinding.api] async call[url: http://10.0.101.20:8080/zstack/api/, response: {"org.zstack.network.service.lb.APIAddVmNicToLoadBalancerEvent":{"success":false,"error":{"code":"SYS.1006","description":"An operation failed","details":"not all arguments converted during string formatting"}}}] after 1000ms

**Comment by youyk** [comment]
DEBUG:urllib3.connectionpool:"POST /zstack/asyncrest/callback HTTP/1.1" 200 0
WARNING:virtualrouter.virtualrouter:not all arguments converted during string formatting
Traceback (most recent call last):
  File "/var/lib/zstack/virtualenv/virtualrouter/lib/python2.6/site-packages/virtualrouter/virtualrouter.py", line 49, in wrap
    return func(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/virtualrouter/lib/python2.6/site-packages/zstacklib/utils/lock.py", line 55, in inner
    retval = f(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/virtualrouter/lib/python2.6/site-packages/virtualrouter/plugins/lb.py", line 120, in refresh
    self._refresh(to)
  File "/var/lib/zstack/virtualenv/virtualrouter/lib/python2.6/site-packages/zstacklib/utils/rollback.py", line 41, in wrap
    logger.warn('exception when calling rollback functions' % content)
TypeError: not all arguments converted during string formatting

**Comment by youyk** [comment]
The comment 1 is the original failure reason, which will trigger the rollback and the rollback will failed as comment 3. In management log, we will see the comment 2.

When this issue happens, the created vip won't be able to be deleted. will report a new bug

**Comment by youyk** [comment]
This bug is triggered by #114 . When VR doesn't release previous VIP IP address and when new LB uses the old VIP address will trigger this bug.

**Comment by zstackorg** [comment]
so close it
