### ISSUE TITLE
Exception when rolling back flows after failing to connect VR

### ISSUE THREAD

**Issue by zxwing** [zstackorg/zstack#141]
015-10-14 10:27:27,251 WARN  [SqlExceptionHelper] (zs-thread-46) SQL Error: 1048, SQLState: 23000
2015-10-14 10:27:27,251 ERROR [SqlExceptionHelper] (zs-thread-46) Column 'status' cannot be null
2015-10-14 10:27:27,253 WARN  [SimpleFlowChain] (zs-thread-46) [FlowChain: reboot-vm-d7ad8804f53c43cd86f6ac3470e48cb2] unhandled exception when rollback flow[], continue to next rollback
org.springframework.orm.jpa.JpaSystemException: org.hibernate.exception.ConstraintViolationException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:418) ~[spring-orm-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.orm.jpa.aspectj.JpaExceptionTranslatorAspect.ajc$afterThrowing$org_springframework_orm_jpa_aspectj_JpaExceptionTranslatorAspect$1$18a1ac9(JpaExceptionTranslatorAspect.aj:33) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.zstack.core.db.DatabaseFacadeImpl$EntityInfo.update_aroundBody0(DatabaseFacadeImpl.java:256) ~[core-0.9.0.jar:?]
	at org.zstack.core.db.DatabaseFacadeImpl$EntityInfo$AjcClosure1.run(DatabaseFacadeImpl.java:1) ~[core-0.9.0.jar:?]
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:59) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:65) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262) ~[spring-tx-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:63) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.zstack.core.db.DatabaseFacadeImpl$EntityInfo.update(DatabaseFacadeImpl.java:252) ~[core-0.9.0.jar:?]
	at org.zstack.core.db.DatabaseFacadeImpl$EntityInfo.updateAndRefresh(DatabaseFacadeImpl.java:274) ~[core-0.9.0.jar:?]
	at org.zstack.core.db.DatabaseFacadeImpl.updateAndRefresh(DatabaseFacadeImpl.java:476) ~[core-0.9.0.jar:?]
	at org.zstack.appliancevm.ApplianceVmBase$8.rollback(ApplianceVmBase.java:497) ~[applianceVm-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollbackFlow(SimpleFlowChain.java:204) [core-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollback(SimpleFlowChain.java:266) [core-0.9.0.jar:?]
	at org.zstack.compute.vm.VmRebootOnHypervisorFlow.rollback(VmRebootOnHypervisorFlow.java:49) [compute-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollbackFlow(SimpleFlowChain.java:204) [core-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollback(SimpleFlowChain.java:266) [core-0.9.0.jar:?]
	at org.zstack.header.core.workflow.NoRollbackFlow.rollback(NoRollbackFlow.java:13) [header-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollbackFlow(SimpleFlowChain.java:204) [core-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollback(SimpleFlowChain.java:266) [core-0.9.0.jar:?]
	at org.zstack.header.core.workflow.NoRollbackFlow.rollback(NoRollbackFlow.java:13) [header-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollbackFlow(SimpleFlowChain.java:204) [core-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollback(SimpleFlowChain.java:266) [core-0.9.0.jar:?]
	at org.zstack.header.core.workflow.NoRollbackFlow.rollback(NoRollbackFlow.java:13) [header-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollbackFlow(SimpleFlowChain.java:204) [core-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollback(SimpleFlowChain.java:266) [core-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.fail(SimpleFlowChain.java:298) [core-0.9.0.jar:?]
	at org.zstack.appliancevm.ApplianceVmDeployAgentFlow$1$4.handle(ApplianceVmDeployAgentFlow.java:120) [applianceVm-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.callErrorHandler(SimpleFlowChain.java:217) [core-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollback(SimpleFlowChain.java:241) [core-0.9.0.jar:?]
	at org.zstack.header.core.workflow.NoRollbackFlow.rollback(NoRollbackFlow.java:13) [header-0.9.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.rollbackFlow(SimpleFlowChain.java:204) [core-0.9.0.jar:?

**Comment by zxwing** [comment]
fixed in upstream
