### ISSUE TITLE
service agent won't restart service when doing reconnect

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#170]
For example, if user manually restart zstack-sftpbackupstorage service, the service will miss some variables. ZStack could still connected with it, since its port is open. But this will lead AddImage failed like: 

WARNING:sftpbackupstorage.sftpbackupstorage:must be string, not None
Traceback (most recent call last):
  File "/var/lib/zstack/virtualenv/sftpbackupstorage/lib/python2.7/site-packages/sftpbackupstorage/sftpbackupstorage.py", line 104, in wrap
    return func(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/sftpbackupstorage/lib/python2.7/site-packages/sftpbackupstorage/sftpbackupstorage.py", line 239, in download_image
    (total, avail) = self.get_capacity()
  File "/var/lib/zstack/virtualenv/sftpbackupstorage/lib/python2.7/site-packages/sftpbackupstorage/sftpbackupstorage.py", line 143, in get_capacity
    total = linux.get_total_disk_size(self.storage_path)
  File "/var/lib/zstack/virtualenv/sftpbackupstorage/lib/python2.7/site-packages/zstacklib/utils/linux.py", line 142, in get_total_disk_size
    stat = os.statvfs(dir_path)
TypeError: must be string, not None

Manually ReconnectSftpBackupStorage also can't fix this problem. The work around has to be manually kill the zstack-sftpbackupstorage process in image server, then redo reconnect API.

We need to support restart zstack agent service, when calling reconnect agent.

**Comment by zxwing** [comment]
fixed in f88c66a131f328a60f27bd27763e60206239e8cf(utiltiy)
fixed 3c5dc1d3ef779f19f51bfb937b8f1e99d46f9fb0(zstack)
