### ISSUE TITLE
VmCreation failure on VirtualRouterSyncDnsOnStartFlow

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#203]
2016-01-22 12:51:55,701 WARN  [SimpleFlowChain] (zs-thread-99) [FlowChain: create-appliancevm-1dab31ccc17a4c248c1c212452d737cd] unhandled exception when executing flow[org.zstack.network.service.virtualrouter.dns.VirtualRouterSyncDnsOnStartFlow], start to rollback
org.zstack.header.apimediator.ApiMessageInterceptionException
    at org.zstack.compute.vm.VmInstanceManagerImpl$5.changeVmIp(VmInstanceManagerImpl.java:503) ~[compute-0.9.0.jar:?]
    at org.zstack.compute.vm.VmInstanceManagerImpl$5.tagPreCreated(VmInstanceManagerImpl.java:512) ~[compute-0.9.0.jar:?]
    at org.zstack.tag.SystemTag.callCreatedJudger(SystemTag.java:64) ~[tag-0.9.0.jar:?]
    at org.zstack.tag.TagManagerImpl.preTagCreated(TagManagerImpl.java:722) ~[tag-0.9.0.jar:?]
    at org.zstack.tag.TagManagerImpl.createTag(TagManagerImpl.java:209) ~[tag-0.9.0.jar:?]
    at org.zstack.tag.TagManagerImpl.createSysTag(TagManagerImpl.java:305) ~[tag-0.9.0.jar:?]
    at org.zstack.tag.SystemTag.createTag(SystemTag.java:219) ~[tag-0.9.0.jar:?]
    at org.zstack.tag.SystemTag.createInherentTag(SystemTag.java:238) ~[tag-0.9.0.jar:?]
    at org.zstack.network.service.virtualrouter.VirtualRouterRoleManager.makeDnsRole(VirtualRouterRoleManager.java:18) ~[virtualRouterProvider-0.9.0.jar:?]
    at org.zstack.network.service.virtualrouter.dns.VirtualRouterSyncDnsOnStartFlow.run(VirtualRouterSyncDnsOnStartFlow.java:58) ~[virtualRouterProvider-0.9.0.jar:?]
    at org.zstack.core.workflow.SimpleFlowChain.runFlow(SimpleFlowChain.java:189) [core-0.9.0.jar:?]
    at org.zstack.core.workflow.SimpleFlowChain.next(SimpleFlowChain.java:349) [core-0.9.0.jar:?]

**Comment by zxwing** [comment]
fixed in d16d0eefd712905c0709a937e3a6b4a7aca47cb9
