### ISSUE TITLE
attach iscsi volume failed, after create snapshot

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#39]
2015-06-12 00:09:09,667 TRACE [CloudBusImpl2] (pool-3-thread-3) [msg received]: {"org.zstack.header.vm.AttachDataVolumeToVmMsg":{"volume":{"uuid":"fe037288083d48dfbd11bb754c83010b","name":"data volume created by sp: dd8065b57bf3414ba525392f00592b2e","primaryStorageUuid":"49a39d25817348ebbeb756bbcc6ac16a","vmInstanceUuid":"f465d817ea2542ff8cd08b0b8e968e74","installPath":"/home/btrfs/dataVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-fe037288083d48dfbd11bb754c83010b/fe037288083d48dfbd11bb754c83010b.img","type":"Data","size":10485760,"state":"Enabled","status":"Ready","createDate":"Jun 12, 2015 12:09:05 AM","lastOpDate":"Jun 12, 2015 12:09:05 AM"},"vmInstanceUuid":"f465d817ea2542ff8cd08b0b8e968e74","timeout":1800000,"headers":{"correlationId":"2459ae77a7f04e4a8b43b218b0ff5479","replyTo":"zstack.message.cloudbus.9ba08e94954e45ad817fe81ac7674f97","noReply":"false","schema":{"org.zstack.header.volume.VolumeInventory":["volume"]}},"id":"2459ae77a7f04e4a8b43b218b0ff5479","serviceId":"vmInstance.9ba08e94954e45ad817fe81ac7674f97","creatingTime":1434038949666}}
2015-06-12 00:09:09,669 WARN  [AsyncSafeAspect] (zs-thread-27) unhandled exception happened when calling protected void org.zstack.compute.vm.VmInstanceBase.attachVolume(org.zstack.header.vm.AttachDataVolumeToVmMsg, org.zstack.header.core.NoErrorCompletion), 1
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.zstack.storage.primary.iscsi.IscsiVolumePath.disassemble(IscsiVolumePath.java:45) ~[iscsiPrimaryStorage-0.6.0.jar:?]
    at org.zstack.storage.primary.iscsi.IscsiFileSystemPrimaryStorageTargetExtension.createTarget(IscsiFileSystemPrimaryStorageTargetExtension.java:128) ~[iscsiPrimaryStorage-0.6.0.jar:?]
    at org.zstack.storage.primary.iscsi.IscsiFileSystemPrimaryStorageTargetExtension.preAttachVolume(IscsiFileSystemPrimaryStorageTargetExtension.java:189) ~[iscsiPrimaryStorage-0.6.0.jar:?]
    at org.zstack.compute.vm.VmInstanceExtensionPointEmitter.preAttachVolume(VmInstanceExtensionPointEmitter.java:303) ~[compute-0.6.0.jar:?]
    at org.zstack.compute.vm.VmInstanceBase.attachVolume_aroundBody10(VmInstanceBase.java:1130) ~[compute-0.6.0.jar:?]
    at org.zstack.compute.vm.VmInstanceBase$AjcClosure11.run(VmInstanceBase.java:1) ~[compute-0.6.0.jar:?]
    at org.zstack.core.aspect.AsyncSafeAspect.ajc$around$org_zstack_core_aspect_AsyncSafeAspect$1$c4af5facproceed(AsyncSafeAspect.aj:1) ~[core-0.6.0.jar:?]
    at org.zstack.core.aspect.AsyncSafeAspect.ajc$around$org_zstack_core_aspect_AsyncSafeAspect$1$c4af5fac(AsyncSafeAspect.aj:84) [core-0.6.0.jar:?]
    at org.zstack.compute.vm.VmInstanceBase.attachVolume(VmInstanceBase.java:1118) [compute-0.6.0.jar:?]
    at org.zstack.compute.vm.VmInstanceBase$8.run_aroundBody0(VmInstanceBase.java:418) [compute-0.6.0.jar:?]
    at org.zstack.compute.vm.VmInstanceBase$8$AjcClosure1.run(VmInstanceBase.java:1) [compute-0.6.0.jar:?]
    at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$7$fb2da26bproceed(AsyncBackupAspect.aj:1) [core-0.6.0.jar:?]
    at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$7$fb2da26b(AsyncBackupAspect.aj:134) [core-0.6.0.jar:?]
    at org.zstack.compute.vm.VmInstanceBase$8.run(VmInstanceBase.java:417) [compute-0.6.0.jar:?]
    at org.zstack.core.thread.DispatchQueueImpl$ChainFuture.run(DispatchQueueImpl.java:199) [core-0.6.0.jar:?]
    at org.zstack.core.thread.DispatchQueueImpl$ChainTaskQueueWrapper$1.runQueue_aroundBody0(DispatchQueueImpl.java:271) [core-0.6.0.jar:?]
    at org.zstack.core.thread.DispatchQueueImpl$ChainTaskQueueWrapper$1$AjcClosure1.run(DispatchQueueImpl.java:1) [core-0.6.0.jar:?]
    at org.zstack.core.aspect.ThreadAspect.ajc$around$org_zstack_core_aspect_ThreadAspect$4$de40e327proceed(ThreadAspect.aj:1) [core-0.6.0.jar:?]
    at org.zstack.core.aspect.ThreadAspect$4.call(ThreadAspect.aj:145) [core-0.6.0.jar:?]
    at org.zstack.core.aspect.ThreadAspect$4.call(ThreadAspect.aj:1) [core-0.6.0.jar:?]
    at org.zstack.core.thread.ThreadFacadeImpl$Worker.call(ThreadFacadeImpl.java:111) [core-0.6.0.jar:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [?:1.7.0_75]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [?:1.7.0_75]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by youyk** [comment]
has been fixed in https://github.com/zstackorg/zstack-utility/commit/7a8495c63ce747d5ebc1832e42cbeb2a92eac475
