### ISSUE TITLE
zstack management node start failure due to rabbitmq: Attempt to use closed channel

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#45]
2015-06-14 23:39:37,885 WARN  [DispatchQueueImpl] (zs-thread-11) unhandled exception happened when calling sync task[name:run-anisble-for-host-10.0.101.20, class:org.zstack.core.ansible.AnsibleFacadeImpl$1]
com.rabbitmq.client.AlreadyClosedException: clean connection shutdown; reason: Attempt to use closed channel
    at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:190) ~[amqp-client-3.2.1.jar:?]
    at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:291) ~[amqp-client-3.2.1.jar:?]
    at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:636) ~[amqp-client-3.2.1.jar:?]
    at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:619) ~[amqp-client-3.2.1.jar:?]
    at org.zstack.core.cloudbus.CloudBusImpl2$Wire.send(CloudBusImpl2.java:427) ~[core-0.7.0.jar:?]

**Comment by youyk** [comment]
This issue will disappear, after restart rabbitmq-server. Will it be because of zstack upgrading?
