### ISSUE TITLE
Delete iscsi volume snapshot failed

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#47]
2015-06-15 08:31:44,784 DEBUG [SimpleFlowChain] (zs-thread-74) [FlowChain: delete-snapshot-03377a3090074616a53f9da1de99e5ab] start executing flow[merge-volume-snapshots-to-volume]
2015-06-15 08:31:44,785 WARN  [SimpleFlowChain] (zs-thread-74) [FlowChain: delete-snapshot-03377a3090074616a53f9da1de99e5ab] unhandled exception when executing flow[org.zstack.storage.snapshot.VolumeSnapshotTreeBase$4], start to rollback
org.springframework.dao.InvalidDataAccessApiUsageException: id to load is required for loading; nested exception is java.lang.IllegalArgumentException: id to load is required for loading
    at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:384) ~[spring-orm-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.orm.jpa.aspectj.JpaExceptionTranslatorAspect.ajc$afterThrowing$org_springframework_orm_jpa_aspectj_JpaExceptionTranslatorAspect$1$18a1ac9(JpaExceptionTranslatorAspect.aj:33) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.zstack.core.db.DatabaseFacadeImpl.findByUuid_aroundBody2(DatabaseFacadeImpl.java:474) ~[core-0.7.0.jar:?]
    at org.zstack.core.db.DatabaseFacadeImpl$AjcClosure3.run(DatabaseFacadeImpl.java:1) ~[core-0.7.0.jar:?]
    at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:59) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:65) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262) ~[spring-tx-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:63) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.zstack.core.db.DatabaseFacadeImpl.findByUuid(DatabaseFacadeImpl.java:473) ~[core-0.7.0.jar:?]
    at org.zstack.storage.snapshot.VolumeSnapshotTreeBase$4.run(VolumeSnapshotTreeBase.java:276) ~[storage-0.7.0.jar:?]
    at org.zstack.core.workflow.SimpleFlowChain.runFlow(SimpleFlowChain.java:159) [core-0.7.0.jar:?]
    at org.zstack.core.workflow.SimpleFlowChain.next(SimpleFlowChain.java:304) [core-0.7.0.jar:?]
    at org.zstack.storage.snapshot.VolumeSnapshotTreeBase$3$1.success_aroundBody0(VolumeSnapshotTreeBase.java:233) [storage-0.7.0.jar:?]
    at org.zstack.storage.snapshot.VolumeSnapshotTreeBase$3$1$AjcClosure1.run(VolumeSnapshotTreeBase.java:1) [storage-0.7.0.jar:?]
    at org.zstack.core.aspect.CompletionSingleCallAspect.ajc$around$org_zstack_core_aspect_CompletionSingleCallAspect$1$cecd1872proceed(CompletionSingleCallAspect.aj:1) [core-0.7.0.jar:?]
    at org.zstack.core.aspect.CompletionSingleCallAspect.ajc$around$org_zstack_core_aspect_CompletionSingleCallAspect$1$cecd1872(CompletionSingleCallAspect.aj:15) [core-0.7.0.jar:?]
    at org.zstack.storage.snapshot.VolumeSnapshotTreeBase$3$1.success_aroundBody2(VolumeSnapshotTreeBase.java:232) [storage-0.7.0.jar:?]
    at org.zstack.storage.snapshot.VolumeSnapshotTreeBase$3$1$AjcClosure3.run(VolumeSnapshotTreeBase.java:1) [storage-0.7.0.jar:?]
    at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$1$cecd1872proceed(AsyncBackupAspect.aj:1) [core-0.7.0.jar:?]
    at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$1$cecd1872(AsyncBackupAspect.aj:86) [core-0.7.0.jar:?]
    at org.zstack.storage.snapshot.VolumeSnapshotTreeBase$3$1.success(VolumeSnapshotTreeBase.java:232) [storage-0.7.0.jar:?]
    at org.zstack.storage.snapshot.VolumeSnapshotTreeBase$13.run_aroundBody0(VolumeSnapshotTreeBase.java:646) [storage-0.7.0.jar:?]
    at org.zstack.storage.snapshot.VolumeSnapshotTreeBase$13$AjcClosure1.run(VolumeSnapshotTreeBase.java:1) [storage-0.7.0.jar:?]
    at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$6$545faac6proceed(AsyncBackupAspect.aj:1) [core-0.7.0.jar:?]
    at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$6$545faac6(AsyncBackupAspect.aj:126) [core-0.7.0.jar:?]
    at org.zstack.storage.snapshot.VolumeSnapshotTreeBase$13.run(VolumeSnapshotTreeBase.java:627) [storage-0.7.0.jar:?]
    at org.zstack.core.cloudbus.CloudBusImpl2$4.ack(CloudBusImpl2.java:1328) [core-0.7.0.jar:?]
    at org.zstack.core.cloudbus.CloudBusImpl2$1.handle_aroundBody0(CloudBusImpl2.java:317) [core-0.7.0.jar:?]

**Comment by zxwing** [comment]
e03baa1c6712aa7c70bda90bc0ede473e24e1c21
