### ISSUE TITLE
iscsi volume vm creation failure

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#54]
ApiError: API call[org.zstack.header.vm.APICreateVmInstanceEvent] failed because [code: SYS.1006, description: An operation failed, details: failed to start vm[uuid:2a0484e7cfd44fa38bcdb1f2ac534987 name:virtualRouter.l3.4822fbf4b9554deb9f3c1b534b1535b7] on kvm host[uuid:acc8e4860fd94d2aa21427d1217e85a5, ip:10.1.101.21], because 'IscsiLogin' object has no attribute 'lun']

WARNING:kvmagent.kvmagent:'IscsiLogin' object has no attribute 'lun'
Traceback (most recent call last):
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/kvmagent.py", line 134, in wrap
    return func(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 1196, in start_vm
    self._start_vm(cmd)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 1175, in _start_vm
    vm = Vm.from_StartVmCmd(cmd)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 1133, in from_StartVmCmd
    make_volumes()
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 1073, in make_volumes
    iscsibased_volume(dev_letter, v.useVirtio)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 1061, in iscsibased_volume
    blk_iscsi()
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 1046, in blk_iscsi
    devices.append(bi.to_xmlobject())
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 202, in to_xmlobject
    device_path = self._login_portal()
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 199, in _login_portal   return login.login()
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/zstacklib/utils/lock.py", line 45, in inner
    retval = f(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 161, in login
    device_path = os.path.join('/dev/disk/by-path/', 'ip-%s:%s-iscsi-%s-lun-%s' % (self.server_hostname, self.server_port, self.target, self.lun))
AttributeError: 'IscsiLogin' object has no attribute 'lun'

**Comment by zxwing** [comment]
cb1ead957bd7b1e4b8c93009c4232fcb0c31807f
