### ISSUE TITLE
Fail to create Volume Template from Data Volume in Local Storage Primary Storage

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#63]
The error log is like:

2015-07-08 15:41:32,550 WARN  [RestTemplate] (zs-thread-60) POST request for "http://10.0.101.20:7070/localstorage/volume/createtemplate" resulted in 404 (Not Found); invoking error handler
2015-07-08 15:41:32,550 WARN  [RESTFacadeImpl] (zs-thread-60) Unable to post to http://10.0.101.20:7070/localstorage/volume/createtemplate
org.springframework.web.client.HttpClientErrorException: 404 Not Found
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:588) ~[spring-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546) ~[spring-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:502) ~[spring-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:444) ~[spring-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
    at org.zstack.core.rest.RESTFacadeImpl.asyncJsonPost(RESTFacadeImpl.java:222) [core-0.7.0.jar:?]
    at org.zstack.kvm.KVMHost.executeAsyncHttpCall_aroundBody2(KVMHost.java:290) [kvm-0.7.0.jar:?]
    at org.zstack.kvm.KVMHost$AjcClosure3.run(KVMHost.java:1) [kvm-0.7.0.jar:?]
    at org.zstack.core.aspect.AsyncSafeAspect.ajc$around$org_zstack_core_aspect_AsyncSafeAspect$1$c4af5facproceed(AsyncSafeAspect.aj:1) [core-0.7.0.jar:?]

**Comment by zxwing** [comment]
fixed in d2fb7d4eb25f13174816e8971889b978001c1b54 (zstack)
fixed in f93c4799ba9686c5fcf98206c4e669cdd8e1987c (zstack-utility)
