### ISSUE TITLE
keep attach/detach nic might fail

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#77]
This issue can only be reproduced by case: virtualrouter/vlan/test_attach_nic_reboot_vm.py

The error log:
API call[org.zstack.header.vm.APIAttachNicToVmEvent] failed because [code: SYS.1001, description: A message or a operation timeout, details: failed to attach nic[uuid:597e3e6aebaf47639f00b771c10e4d24, vm:91931e0042414f65b67b0f4f76a42158] on kvm host[uuid:36b23af291054073b0177010866bc587, ip:10.0.101.20],because Unable to create tap device vnic6.1: Device or resource busy]

INFO:cherrypy.access.25859088:10.0.101.20 - - [21/Jul/2015:00:03:18] "POST /vm/attachnic HTTP/1.1" 200 - "" "Java/1.7.0_75"
WARNING:kvmagent.kvmagent:Unable to create tap device vnic6.1: Device or resource busy
Traceback (most recent call last):
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/kvmagent.py", line 134, in wrap
    return func(*args, **kwargs)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 1243, in attach_nic
    vm.attach_nic(cmd)
  File "/var/lib/zstack/virtualenv/kvm/lib/python2.6/site-packages/kvmagent/plugins/vm_plugin.py", line 921, in attach_nic
    self.domain.attachDeviceFlags(xml, libvirt.VIR_DOMAIN_AFFECT_LIVE)
  File "/usr/lib64/python2.6/site-packages/libvirt.py", line 427, in attachDeviceFlags
    if ret == -1: raise libvirtError ('virDomainAttachDeviceFlags() failed', dom=self)
libvirtError: Unable to create tap device vnic6.1: Device or resource busy

**Comment by zxwing** [comment]
fixed in upstream
