### ISSUE TITLE
Installation identify can't start management server for all-in-one

### ISSUE THREAD

**Issue by xianke9** [zstackorg/zstack#8]
......................
 7. Start ZStack Server:\n----------------
    Start ZStack management node:successfully stopped management node
successfully started Tomcat container; now it's waiting for the management node ready for serving APIs, which may take a few seconds
ERROR: no management-node-ready message received within 120 seconds, please check error in log file ar/log/zstack/management-server.log
restart zstack service .... FAILED
FAIL

  Reason: failed to start zstack

The detailed installation log could be found in /tmp/zstack_installation.log

=====================================
2015-04-23 13:26:02,059 WARN  [DispatchQueueImpl] (zs-thread-11) unhandled exception happened when calling sync task[name:run-anisble-for-host-9.110.85.55, class:org.zstack.core.ansible.AnsibleFacadeImpl$1]
com.rabbitmq.client.AlreadyClosedException: clean connection shutdown; reason: Attempt to use closed channel
        at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:190) ~[amqp-client-3.2.1.jar:?]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:291) ~[amqp-client-3.2.1.jar:?]
        at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:636) ~[amqp-client-3.2.1.jar:?]
        at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:619) ~[amqp-client-3.2.1.jar:?]
        at org.zstack.core.cloudbus.CloudBusImpl2$Wire.send(CloudBusImpl2.java:427) ~[core-0.6.0.jar:?]
        at org.zstack.core.cloudbus.CloudBusImpl2.reply(CloudBusImpl2.java:1576) ~[core-0.6.0.jar:?]
        at org.zstack.core.ansible.AnsibleFacadeImpl$1$1.fail_aroundBody4(AnsibleFacadeImpl.java:170) ~[core-0.6.0.jar:?]
        at org.zstack.core.ansible.AnsibleFacadeImpl$1$1$AjcClosure5.run(AnsibleFacadeImpl.java:1) ~[core-0.6.0.jar:?]
        at org.zstack.core.aspect.CompletionSingleCallAspect.ajc$around$org_zstack_core_aspect_CompletionSingleCallAspect$2$4b6fbdf7proceed(CompletionSingleCallAspect.aj:1) ~[core-0.6.0.jar:?]
        at org.zstack.core.aspect.CompletionSingleCallAspect.ajc$around$org_zstack_core_aspect_CompletionSingleCallAspect$2$4b6fbdf7(CompletionSingleCallAspect.aj:24) ~[core-0.6.0.jar:?]
        at org.zstack.core.ansible.AnsibleFacadeImpl$1$1.fail(AnsibleFacadeImpl.java:168) ~[core-0.6.0.jar:?]
        at org.zstack.core.aspect.AsyncSafeAspect$1.call(AsyncSafeAspect.aj:44) ~[core-0.6.0.jar:?]
        at org.zstack.core.aspect.AsyncSafeAspect.ajc$around$org_zstack_core_aspect_AsyncSafeAspect$1$c4af5fac(AsyncSafeAspect.aj:104) ~[core-0.6.0.jar:?]
        at org.zstack.core.ansible.AnsibleFacadeImpl$1.run(AnsibleFacadeImpl.java:125) ~[core-0.6.0.jar:?]
        at org.zstack.core.ansible.AnsibleFacadeImpl$1.call(AnsibleFacadeImpl.java:161) ~[core-0.6.0.jar:?]
        at org.zstack.core.thread.DispatchQueueImpl$SyncTaskFuture.run(DispatchQueueImpl.java:59) [core-0.6.0.jar:?]
        at org.zstack.core.thread.DispatchQueueImpl$SyncTaskQueueWrapper$1.run(DispatchQueueImpl.java:114) [core-0.6.0.jar:?]
        at org.zstack.core.thread.DispatchQueueImpl$SyncTaskQueueWrapper$1.call(DispatchQueueImpl.java:132) [core-0.6.0.jar:?]
        at org.zstack.core.thread.DispatchQueueImpl$SyncTaskQueueWrapper$1.call(DispatchQueueImpl.java:1) [core-0.6.0.jar:?]
        at org.zstack.core.thread.ThreadFacadeImpl$Worker.call(ThreadFacadeImpl.java:111) [core-0.6.0.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [?:1.7.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [?:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [?:1.7.0_45]

============================================
/etc/init.d/rabbitmq-server status
..................
{running_applications,[{rabbit,"RabbitMQ","3.3.4"},

**Comment by zxwing** [comment]
not seen in current mainline.
