### ISSUE TITLE
UpdateImage with platform=Paravirtualization failed

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#88]
2015-08-05 01:20:43,572 TRACE [CloudBusImpl2] (pool-3-thread-3) [msg received]: {"org.zstack.header.image.APIUpdateImageMsg":{"uuid":"5e40b7d5fed442848830716bfe71ec2e","platform":"Paravirtualization","session":{"uuid":"ecba5456bed24754a8aa363363d7e33f","accountUuid":"36c27e8ff05c4780bf6d2fa65700f22e","userUuid":"36c27e8ff05c4780bf6d2fa65700f22e","expiredDate":"Aug 5, 2015 3:20:21 AM","createDate":"Aug 5, 2015 1:20:21 AM"},"timeout":1800000,"headers":{"correlationId":"b900d6253ecd4cc4a8efe53dcb55bd7a","replyTo":"zstack.message.cloudbus.520dd673b67045278b4f3f3b6ba99458","noReply":"false","schema":{}},"id":"b900d6253ecd4cc4a8efe53dcb55bd7a","serviceId":"image.520dd673b67045278b4f3f3b6ba99458","creatingTime":1438708843529}}
2015-08-05 01:20:43,618 WARN  [SqlExceptionHelper] (zs-thread-93) SQL Error: 1406, SQLState: 22001
2015-08-05 01:20:43,618 ERROR [SqlExceptionHelper] (zs-thread-93) Data truncation: Data too long for column 'platform' at row 1

rg.springframework.orm.jpa.JpaSystemException: org.hibernate.exception.DataException: could not execute statement; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute statement
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:418) ~[spring-orm-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.orm.jpa.aspectj.JpaExceptionTranslatorAspect.ajc$afterThrowing$org_springframework_orm_jpa_aspectj_JpaExceptionTranslatorAspect$1$18a1ac9(JpaExceptionTranslatorAspect.aj:33) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.zstack.core.db.DatabaseFacadeImpl$EntityInfo.update_aroundBody0(DatabaseFacadeImpl.java:254) ~[core-0.8.0.jar:?]
        at org.zstack.core.db.DatabaseFacadeImpl$EntityInfo$AjcClosure1.run(DatabaseFacadeImpl.java:1) ~[core-0.8.0.jar:?]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:59) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:65) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
...

**Comment by youyk** [comment]
If set Paravirtualization in zstack database, QueryImage will fail:

>>>QueryImage
API call[org.zstack.header.message.APIReply] failed because [code: SYS.1000, description: An internal error happened in system, details: Unknown name value [Paravirtualizati] for enum class [org.zstack.header.image.ImagePlatform]; nested exception is java.lang.IllegalArgumentException: Unknown name value [Paravirtualizati] for enum class [org.zstack.header.image.ImagePlatform]]

**Comment by zxwing** [comment]
fixed in db75fdde5c3b091cbbbb5986f2191d546f854c2c
