### ISSUE TITLE
iso duplicate primary key issue when downloading iso to local storage

### ISSUE THREAD

**Issue by zxwing** [zstackorg/zstack#95]
2015-08-14 10:23:54,286 ERROR [SqlExceptionHelper] (zs-thread-7) Duplicate entry '10b5206a22f14e32a80edc1823c93ca0' for key 'PRIMARY'
2015-08-14 10:23:54,287 WARN  [CloudBusImpl2] (zs-thread-7) unhandled throwable happened when dealing with message[org.zstack.header.storage.primary.DownloadIsoToPrimaryStorageMsg], dump: {"org.zstack.header.storage.primary.DownloadIsoToPrimaryStorageMsg":{"primaryStorageUuid":"30ac23f8d8e04a09af2fb558dfbf5721","isoSpec":{"inventory":{"uuid":"10b5206a22f14e32a80edc1823c93ca0","name":"win7","state":"Enabled","status":"Ready","size":2759524352,"md5Sum":"not calculated","url":"http://10.177.11.103/windows7_Ultimate_x64.iso","mediaType":"ISO","type":"zstack","platform":"Windows","format":"iso","system":false,"createDate":"Aug 13, 2015 5:26:39 PM","lastOpDate":"Aug 13, 2015 5:26:39 PM","backupStorageRefs":[{"id":5,"imageUuid":"10b5206a22f14e32a80edc1823c93ca0","backupStorageUuid":"d3e4789eb8394d70be599ea222b055c2","installPath":"/backupStorage/dataVolumeTemplates/acct-36c27e8ff05c4780bf6d2fa65700f22e/10b5206a22f14e32a80edc1823c93ca0/windows7_Ultimate_x64.iso","createDate":"Aug 13, 2015 5:26:45 PM","lastOpDate":"Aug 13, 2015 5:26:45 PM"}]},"selectedBackupStorage":{"id":5,"imageUuid":"10b5206a22f14e32a80edc1823c93ca0","backupStorageUuid":"d3e4789eb8394d70be599ea222b055c2","installPath":"/backupStorage/dataVolumeTemplates/acct-36c27e8ff05c4780bf6d2fa65700f22e/10b5206a22f14e32a80edc1823c93ca0/windows7_Ultimate_x64.iso","createDate":"Aug 13, 2015 5:26:45 PM","lastOpDate":"Aug 13, 2015 5:26:45 PM"}},"vmInstanceUuid":"5379e86ad4e04a6c9ad80c7170b8ce45","destHostUuid":"0624d46ae2fa4568b70ba7729d0b25e1","timeout":1800000,"headers":{"correlationId":"ce3f9722e8e34caab61efc08a8fd06ed","replyTo":"zstack.message.cloudbus.20d167e80b264226893f40299cd41697","noReply":"false","schema":{"org.zstack.header.image.ImageInventory":["isoSpec.inventory"],"org.zstack.header.image.ImageBackupStorageRefInventory":["isoSpec.inventory.backupStorageRefs[0]","isoSpec.selectedBackupStorage"]}},"id":"ce3f9722e8e34caab61efc08a8fd06ed","serviceId":"storage.primary.20d167e80b264226893f40299cd41697","creatingTime":1439519034272}}
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:189) ~[spring-orm-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:155) ~[spring-orm-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:519) ~[spring-orm-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:757) ~[spring-tx-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:726) ~[spring-tx-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:478) ~[spring-tx-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:272) ~[spring-tx-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:63) ~[spring-aspects-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.zstack.core.db.DatabaseFacadeImpl.doPersist(DatabaseFacadeImpl.java:483) ~[core-0.8.0.jar:?]
	at org.zstack.core.db.DatabaseFacadeImpl.persist_aroundBody6(DatabaseFacadeImpl.java:496) ~[core-0.8.0.jar:?]
	at org.zstack.core.db.DatabaseFacadeImpl$AjcClosure7.run(DatabaseFacadeImpl.java:1) ~[core-0.8.0.jar:?]
	at org.zstack.core.aspect.DbDeadlockAspect.ajc$around$org_zstack_core_aspect_DbDeadlockAspect$1$9352950eproceed(DbDeadlockAspect.aj:1) ~[core-0.8.0.jar:?]
	at org.zstack.core.aspect.DbDeadlockAspect.ajc$around$org_zstack_core_aspect_DbDeadlockAspect$1$9352950e(DbDeadlockAspect.aj:21) ~[core-0.8.0.jar:?]
	at org.zstack.core.db.DatabaseFacadeImpl.persist(DatabaseFacadeImpl.java:495) ~[core-0.8.0.jar:?]
	at org.zstack.core.db.DatabaseFacadeImpl.persist(DatabaseFacadeImpl.java:408) ~[core-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase.createResourceRefVO(LocalStorageBase.java:518) ~[localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase.access$4(LocalStorageBase.java:511) ~[localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase$13$3.handle_aroundBody0(LocalStorageBase.java:778) ~[localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase$13$3$AjcClosure1.run(LocalStorageBase.java:1) ~[localstorage-0.8.0.jar:?]
	at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$11$9bf4943eproceed(AsyncBackupAspect.aj:1) [core-0.8.0.jar:?]
	at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$11$9bf4943e(AsyncBackupAspect.aj:166) [core-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase$13$3.handle(LocalStorageBase.java:776) [localstorage-0.8.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.callDoneHandler(SimpleFlowChain.java:287) [core-0.8.0.jar:?]
	at org.zstack.core.workflow.SimpleFlowChain.next(SimpleFlowChain.java:317) [core-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase$13$2$1.success_aroundBody0(LocalStorageBase.java:762) [localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase$13$2$1$AjcClosure1.run(LocalStorageBase.java:1) [localstorage-0.8.0.jar:?]
	at org.zstack.core.aspect.CompletionSingleCallAspect.ajc$around$org_zstack_core_aspect_CompletionSingleCallAspect$3$788c73d1proceed(CompletionSingleCallAspect.aj:1) [core-0.8.0.jar:?]
	at org.zstack.core.aspect.CompletionSingleCallAspect.ajc$around$org_zstack_core_aspect_CompletionSingleCallAspect$3$788c73d1(CompletionSingleCallAspect.aj:33) [core-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase$13$2$1.success_aroundBody2(LocalStorageBase.java:760) [localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase$13$2$1$AjcClosure3.run(LocalStorageBase.java:1) [localstorage-0.8.0.jar:?]
	at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$2$788c73d1proceed(AsyncBackupAspect.aj:1) [core-0.8.0.jar:?]
	at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$2$788c73d1(AsyncBackupAspect.aj:94) [core-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase$13$2$1.success(LocalStorageBase.java:760) [localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageBase$13$2$1.success(LocalStorageBase.java:1) [localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageKvmBackend$10.success_aroundBody0(LocalStorageKvmBackend.java:881) [localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageKvmBackend$10$AjcClosure1.run(LocalStorageKvmBackend.java:1) [localstorage-0.8.0.jar:?]
	at org.zstack.core.aspect.CompletionSingleCallAspect.ajc$around$org_zstack_core_aspect_CompletionSingleCallAspect$3$788c73d1proceed(CompletionSingleCallAspect.aj:1) [core-0.8.0.jar:?]
	at org.zstack.core.aspect.CompletionSingleCallAspect.ajc$around$org_zstack_core_aspect_CompletionSingleCallAspect$3$788c73d1(CompletionSingleCallAspect.aj:33) [core-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageKvmBackend$10.success_aroundBody2(LocalStorageKvmBackend.java:878) [localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageKvmBackend$10$AjcClosure3.run(LocalStorageKvmBackend.java:1) [localstorage-0.8.0.jar:?]
	at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$2$788c73d1proceed(AsyncBackupAspect.aj:1) [core-0.8.0.jar:?]
	at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$2$788c73d1(AsyncBackupAspect.aj:94) [core-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageKvmBackend$10.success(LocalStorageKvmBackend.java:878) [localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageKvmBackend$10.success(LocalStorageKvmBackend.java:1) [localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageKvmBackend$ImageCache$1.run_aroundBody0(LocalStorageKvmBackend.java:624) [localstorage-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageKvmBackend$ImageCache$1$AjcClosure1.run(LocalStorageKvmBackend.java:1) [localstorage-0.8.0.jar:?]
	at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$7$fb2da26bproceed(AsyncBackupAspect.aj:1) [core-0.8.0.jar:?]
	at org.zstack.core.aspect.AsyncBackupAspect.ajc$around$org_zstack_core_aspect_AsyncBackupAspect$7$fb2da26b(AsyncBackupAspect.aj:134) [core-0.8.0.jar:?]
	at org.zstack.storage.primary.local.LocalStorageKvmBackend$ImageCache$1.run(LocalStorageKvmBackend.java:611) [localstorage-0.8.0.jar:?]
	at org.zstack.core.thread.DispatchQueueImpl$ChainFuture.run(DispatchQueueImpl.java:199) [core-0.8.0.jar:?]
	at org.zstack.core.thread.DispatchQueueImpl$ChainTaskQueueWrapper$1.runQueue_aroundBody0(DispatchQueueImpl.java:271) [core-0.8.0.jar:?]
	at org.zstack.core.thread.DispatchQueueImpl$ChainTaskQueueWrapper$1$AjcClosure1.run(DispatchQueueImpl.java:1) [core-0.8.0.jar:?]
	at org.zstack.core.aspect.ThreadAspect.ajc$around$org_zstack_core_aspect_ThreadAspect$4$de40e327proceed(ThreadAspect.aj:1) [core-0.8.0.jar:?]
	at org.zstack.core.aspect.ThreadAspect$4.call(ThreadAspect.aj:145) [core-0.8.0.jar:?]
	at org.zstack.core.aspect.ThreadAspect$4.call(ThreadAspect.aj:1) [core-0.8.0.jar:?]
	at org.zstack.core.thread.ThreadFacadeImpl$Worker.call(ThreadFacadeImpl.java:111) [core-0.8.0.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_85]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [?:1.7.0_85]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [?:1.7.0_85]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_85]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_85]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:74) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:124) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:58) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3079) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3521) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:88) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:395) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:387) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:303) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:404) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:75) ~[hibernate-entitymanager-4.2.11.Final.jar:4.2.11.Final]
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:515) ~[spring-orm-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	... 59 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '10b5206a22f14e32a80edc1823c93ca0' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_85]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_85]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_85]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_85]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.Util.getInstance(Util.java:383) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1049) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4226) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4158) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2840) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2334) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2262) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2246) ~[mysql-connector-java-5.1.31.jar:?]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:435) ~[c3p0-0.9.5-pre10.jar:0.9.5-pre10]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:186) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:58) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3079) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3521) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:88) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:395) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:387) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:303) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1159) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:404) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175) ~[hibernate-core-4.2.11.Final.jar:4.2.11.Final]
	at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:75) ~[hibernate-entitymanager-4.2.11.Final.jar:4.2.11.Final]
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:515) ~[spring-orm-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	... 59 more

**Comment by zxwing** [comment]
fixed in 6e5091d5e94610696bf665b4ac4e2740afd6de6b
