### ISSUE TITLE
Header sub-project build from source code : bad version number found in aspectj.

### ISSUE THREAD

**Issue by cloudtrends** [zstackorg/zstack#97]
hi,all

When I compile zstack from source code by run command : 
    mvn -DskipTests clean install

the process stoped at header sub-project with error : 

 bad version number found in  PATH-OF-ASPECTJ expected 1.6.11 found 1.6.12

detail errors as below :

[INFO] ------------------------------------------------------------------------
[INFO] Building header 0.8.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- aspectj-maven-plugin:1.4:compile (default) @ header ---
[WARNING] bad version number found in C:\Users\Administrator\.m2\repository\org\aspectj\aspectjrt\1.6.12\aspectjrt-1.6.12.jar expected 1.6.11 found 1.6.12
org.aspectj.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 15
        at org.aspectj.apache.bcel.classfile.Constant.readConstant(Constant.java:133)
        at org.aspectj.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:45)
        at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:186)
        at org.aspectj.apache.bcel.classfile.ClassParser.parse(ClassParser.java:131)
        at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:424)
        at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:376)

BTW
 pom.xml   , in the top directory,  the version number of aspectj is <aspectj.version>1.6.12</aspectj.version> .

Which config item makes the conflict happen?

thanks

**Comment by zxwing** [comment]
what is your jvm version? ZStack has not supported Java 8 yet, you need to compile it with Java 7.

**Comment by cloudtrends** [comment]
got it!

I am under Java 8
